### ISSUE TITLE
Errors encountered while setting up self-hosting

### ISSUE THREAD

**Issue by serra-allgood** [ananace/matrix-releasetracker#2]
**Ruby:** 2.6.4, managed with asdf
**Synapse:** 1.3.1

releasetracker.yml
```
---
:backends:
- :access_token: <token with notifications and full user scopes>
  :type: github
  :users:
  - :name: 'serra-allgood' 
    :room: <snip>
:client:
  :hs_url: https://lost-angles.im
  :access_token: <snip>
```

Commands used:
```
<create bot user using register_new_matrix_user, create access token>
git clone <repo> release-tracker
cd release-tracker
bundle install
bundle exec bin/tracker
```

The first error encountered was
```
ArgumentError: Malformed version number string 1.3.1 (b=master,t=v1.3.1,74fb72921)
  /home/matrix/.asdf/installs/ruby/2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/version.rb:212:in `initialize'
  /home/matrix/.asdf/installs/ruby/2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/version.rb:203:in `new'
  /home/matrix/.asdf/installs/ruby/2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/version.rb:203:in `new'
  /home/matrix/release-tracker/lib/matrix_releasetracker/client.rb:66:in `reload!'
  /home/matrix/release-tracker/lib/matrix_releasetracker/client.rb:35:in `initialize'
  /home/matrix/release-tracker/lib/matrix_releasetracker/config.rb:20:in `new'
  /home/matrix/release-tracker/lib/matrix_releasetracker/config.rb:20:in `block in load!'
  /home/matrix/release-tracker/lib/matrix_releasetracker/config.rb:19:in `map'
  /home/matrix/release-tracker/lib/matrix_releasetracker/config.rb:19:in `load!'
  /home/matrix/release-tracker/lib/matrix_releasetracker/config.rb:7:in `load!'
  bin/tracker:85:in `run!'
  bin/tracker:195:in `<top (required)>'
```

Hard coding the api version check to just `'1.3.1'` worked around it, but lead to a chain of minor syntax errors related:
- Accessing hash keys with javascript style dot access
- Hash created with `group_by`, which has a type style of `String => Array<Struct>`, but a subsequent manual addition of `key => value` used a type style of `String => Struct`. A sort on the hash's values, which results in `Array<Array<Struct> | Struct>`, tries to call `date` on each value to sort, but when the `group_by` is successful, `Array` does not have a `date` method. I chained a `flatten` to the `values` call, but I'm not sure if that holds to the proper logic

[This fork and branch](https://github.com/serra-allgood/matrix-releasetracker/tree/serra-allgood/minor-fixes) has the minimum changes I made to get the bot working, plus a clarification in the README that the config needs github usernames (which I think is right?)

Let me know if you'd like a PR opened

**Comment by serra-allgood** [comment]
Hm, looks like there's some strangeness with the `last_check` calls in `bin/tracker`, sometimes the message receiver is a struct and sometimes it's a hash. Don't know what that's about

**Comment by ananace** [comment]
Ah, I can see where most of the problems are arising from.

The project is still in heavy swing, so master is not guaranteed to work at every time. I just pushed a `stable` branch, which I'll try to keep up-to-date with what the actual working point is.
I can see at least one of fix of yours that will impact that code as well though, and at least one change that could cause major issues in a few rare edge cases I've seen.

Do you mind if I repurpose your changes for you? Or would you like to get a full review to do that yourself?

**Comment by serra-allgood** [comment]
Please feel free to use as you'd like! I'll follow along as needed :smiley:

**Comment by ananace** [comment]
I created a [`fixes`](https://github.com/ananace/matrix-releasetracker/tree/fixes) branch off of stable with some of your changes, only in a different manner.  
Hopefully your problems are solved in there.

**Comment by serra-allgood** [comment]
Thanks so much! It looks like there are problems if I include both `access_token` and my GitHub username in `users` for the config file, but making it `:users: []` makes it run smoothly. Should I close this issue?

Aside, I really need to clean up my starred repos, I have way too many, haha.

**Comment by ananace** [comment]
The `:users` key in the backend config is supposed to be handled entirely by the bot, as it's used for data storage purposes due to some early design choices, I really need to clean up that part of the example.
Though considering I'm currently actively removing all types of data storage from the config file, maybe it's better to just let it be for now.
